inveniosoftware/invenio-pages

CHANGES.rst, MANIFEST.in, RELEASE-NOTES.rst, invenio_pages/version.py
Signed-off-by: Jiri Kuncar <jiri.kuncar@cern.ch>
=> Invenio-Pages v0.1.0

invenio_pages/admin.py
* Sets default template and avoids crashing when no template
is specified in admin interface.
Reviewed-by: Jan Aage Lavik <jan.age.lavik@cern.ch>
Signed-off-by: Javier Martin Montull <javier.martin.montull@cern.ch>
=> pages: default page template

AUTHORS.rst, CHANGES.rst, MANIFEST.in, RELEASE-NOTES.rst, invenio_pages/version.py
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>
=> Invenio-Pages v0.1.1

.travis.invenio.cfg, .travis.yml, setup.py, tests/test_pages.py
* Improves Travis CI configuration.  (closes #8)
Signed-off-by: Jiri Kuncar <jiri.kuncar@cern.ch>
=> travis: fix environment creation

invenio_pages/admin.py, invenio_pages/models.py, invenio_pages/upgrades/pages_2014_04_22_new_model.py, invenio_pages/views.py, requirements-devel.txt, setup.py, tests/test_pages.py
=> global: fix invenio_ext imports

CHANGES.rst, RELEASE-NOTES.rst, invenio_pages/version.py
Signed-off-by: Jiri Kuncar <jiri.kuncar@cern.ch>
=> Invenio-Pages v0.1.2

invenio_pages/config.py, invenio_pages/ext.py, invenio_pages/models.py, invenio_pages/templates/invenio_pages/dynamic.html, invenio_pages/views.py, tests/conftest.py, tests/test_invenio_pages.py, tests/test_views.py
* Adds support for rendering pages as templates which allow to include e.g.
configuration variables.
Signed-off-by: Lars Holm Nielsen <lars.holm.nielsen@cern.ch>
=> templates: dynamic page rendering

tests/test_views.py
* Adds a test to verify that current_app and config are not
visible in templates. (closes #23)
Signed-off-by: Sami Hiltunen <sami.mikael.hiltunen@cern.ch>
=> tests: template variable visibility test

CHANGES.rst, RELEASE-NOTES.rst, invenio_pages/version.py
Signed-off-by: Lars Holm Nielsen <lars.holm.nielsen@cern.ch>
=> release: v1.0.0a2

invenio_pages/version.py
Signed-off-by: Lars Holm Nielsen <lars.holm.nielsen@cern.ch>
=> version: post-release bump

.tx/config, invenio_pages/ext.py, invenio_pages/translations/cs/LC_MESSAGES/messages.po, invenio_pages/translations/da/LC_MESSAGES/messages.po, invenio_pages/translations/de/LC_MESSAGES/messages.po, invenio_pages/translations/es/LC_MESSAGES/messages.po, invenio_pages/translations/it/LC_MESSAGES/messages.po, invenio_pages/translations/messages.pot, setup.cfg, setup.py, tests/conftest.py
Signed-off-by: Alizee Pace <alizee.pace@gmail.com>
=> i18n: tx config fix and translation improvements

docs/api.rst, docs/conf.py, invenio_pages/ext.py, invenio_pages/models.py, invenio_pages/views.py, setup.py
* Improves documentation. (addresses #31)
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>
=> docs: addition of param and result sections

.travis.yml, .tx/config, AUTHORS.rst, docs/api.rst, docs/conf.py, docs/index.rst, invenio_pages/__init__.py, invenio_pages/admin.py, setup.py
Signed-off-by: Jiri Kuncar <jiri.kuncar@cern.ch>
=> global: code style and copyrights

MANIFEST.in, README.rst, RELEASE-NOTES.rst, docs/requirements.txt, requirements.py
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>
=> docs: move to readthedocs.io

MANIFEST.in, examples/app-fixtures.sh, examples/app-setup.sh, examples/app-teardown.sh, examples/app.py, examples/templates/app/default.html, invenio_pages/ext.py, tests/test_examples_app.py
* Adds test_examples_app.py. (closes #37)
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>
=> tests: addition of test_examples_app.py

invenio_pages/alembic/145402e8523a_create_pages_table.py, invenio_pages/alembic/98e0a418340d_create_invenio_pages_branch.py, setup.py, tests/test_invenio_pages.py
* closes https://github.com/inveniosoftware/invenio-pages/issues/54
=> alembic: add recipe to create tables

invenio_pages/views.py
* closes https://github.com/inveniosoftware/invenio-pages/issues/58
=> views: add register urls dynamically

invenio_pages/records/errors.py, invenio_pages/records/models.py, invenio_pages/resources/config.py, invenio_pages/resources/resource.py, invenio_pages/services/config.py, invenio_pages/services/permissions.py, invenio_pages/services/results.py, invenio_pages/services/schemas.py, invenio_pages/services/service.py, invenio_pages/views.py, tests/conftest.py, tests/records/test_records.py, tests/resources/test_resources.py, tests/services/test_services.py
Add tests
closes: https://github.com/inveniosoftware/invenio-pages/issues/70
requires: https://github.com/inveniosoftware/invenio-records-resources/pull/437
=> Pages: add C*UD resource, service and record logic

invenio_pages/administration/__init__.py, invenio_pages/administration/views/__init__.py, invenio_pages/administration/views/pages.py, invenio_pages/alembic/__init__.py, invenio_pages/config.py, invenio_pages/records/errors.py, invenio_pages/services/config.py, invenio_pages/services/permissions.py, invenio_pages/services/results.py, invenio_pages/services/schemas.py, invenio_pages/views.py, setup.cfg
closes: #66 
requires: https://github.com/inveniosoftware/invenio-administration/pull/160
Screenshots respectively in Desktop, Laptop and Tablet resolutions.
Search view:
Details view:
Edit view:
=> Pages: integrate with invenio-administration [REQUIRES inveniosoftware/invenio-administration#160]

.github/workflows/tests.yml, CHANGES.rst, invenio_pages/__init__.py, run-tests.sh, setup.cfg
* ci: add search services to tests
=> setup: fix search dependencies

invenio_pages/services/schemas.py
:heart: Thank you for your contribution!
Please describe briefly your pull request.
Ticks in all boxes and 🟢 on all GitHub actions status checks are required to merge:
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license …
=> schema: sanitize page content

CHANGES.rst, invenio_pages/__init__.py
:heart: Thank you for your contribution!
Please describe briefly your pull request.
Ticks in all boxes and 🟢 on all GitHub actions status checks are required to merge:
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license …
=> release: v3.1.0

invenio_pages/administration/views/pages.py, invenio_pages/alembic/1737449793_add_language_and_new_uq.py, invenio_pages/records/models.py, invenio_pages/services/schemas.py, invenio_pages/services/service.py, invenio_pages/views.py, tests/alembic/test_alembic.py, tests/conftest.py, tests/records/test_records.py, tests/resources/test_resources.py, tests/services/test_services.py
:heart: Thank you for your contribution!
> Please describe briefly your pull request.
Ticks in all boxes and 🟢 on all GitHub actions status checks are required to merge:
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect on Discord](https://discord.gg/8qatqBC).
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license your contribution under the …
=> Add i18n support

invenio_pages/resources/config.py, tests/conftest.py
* due to changes in the creation of url it is necessary to set
THEME_FRONTPAGE explicitly
=> fix: add configuration
